# Generated by Django 4.0.4 on 2022-06-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('notice_kind', models.CharField(choices=[('notice', 'Notice'), ('inspection', 'Inspection'), ('event', 'Event')], max_length=12)),
                ('link', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
