# Generated by Django 4.0.4 on 2022-06-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='notice_kind',
            field=models.CharField(choices=[('notice', '공지'), ('inspection', '점검'), ('event', '이벤트')], max_length=12),
        ),
    ]
