# Generated by Django 4.0.4 on 2022-06-12 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='calendar',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_calc_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.symboldata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_calendar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
