# Generated by Django 4.0.4 on 2022-06-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='job_second_class',
            field=models.CharField(blank=True, choices=[('warrior', '전사'), ('wizard', '마법사'), ('archer', '궁수'), ('thief', '도적'), ('pirate', '해적')], max_length=8, null=True),
        ),
    ]
