# Generated by Django 4.0.4 on 2022-06-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_union_job_second_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=8)),
                ('job_first_class', models.CharField(choices=[('warrior', '전사'), ('wizard', '마법사'), ('archer', '궁수'), ('thief', '도적'), ('pirate', '해적')], max_length=8)),
                ('job_second_class', models.CharField(blank=True, choices=[('warrior', '전사'), ('wizard', '마법사'), ('archer', '궁수'), ('thief', '도적'), ('pirate', '해적')], max_length=8, null=True)),
                ('job_group', models.CharField(choices=[('adventurer', '모험가'), ('resistance', '레지스탕스'), ('cygnus', '시그너스'), ('hero', '영웅'), ('nova', '노바'), ('flora', '레프'), ('anima', '아니마'), ('zero', '제로'), ('kinesis', '키네시스')], max_length=10)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
