# Generated by Django 4.0.4 on 2022-06-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_kind', models.CharField(choices=[('arcane', '아케인'), ('authentic', '어센틱')], max_length=10)),
                ('arcane_symbol_kind', models.CharField(blank=True, choices=[('journey', '여로'), ('chuchu', '츄츄'), ('lacheln', '레헬른'), ('arcana', '아르카나'), ('moras', '모라스'), ('esfera', '에스페라')], max_length=10)),
                ('authentic_symbol_kind', models.CharField(blank=True, choices=[('cernium', '세르니움'), ('arcus', '아르크스')], max_length=10)),
                ('max_daily_acquisition', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='calculate',
            name='user',
        ),
    ]
